name: vitamins_app_for_footballer
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  get_it: ^7.2.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  intl: ^0.18.1
  flutter_local_notifications: ^16.1.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: RobotoFlex
      fonts:
        - asset:
            assets/fonts/RobotoFlex-Regular.ttf




